defaults:
  - base_config
  - _self_

  - override hydra/launcher: submitit_slurm 
  # - override hydra/launcher: submitit_local


hydra:
  sweeper:
    params:
      NUM_NETS: 10, 20
      # GENERATIONS: 25, 50, 100
      NET_TRAINING_EPOCHS: 10, 30
      TEMPERATURE: 0.3, 0.5, 0.7

  # SLURM-specific arguments
  launcher:
    tasks_per_node: 1
    cpus_per_task: 1
    gpus_per_node: 1
    timeout_min: 2880
    mem_gb: 30